name: Monthly Dependabot Report

steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-ruby@v1
    with:
      ruby-version: '3.1.3'
  - run: |
      gem install bundler
      bundle install
      bundle exec ruby dependabot_report.rb 2023-01-01 2023-02-01
