name: Monthly Dependabot Report

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

env:
  SLACK_CHANNEL: C03HM8HK0JJ # front-end-arch-chat

jobs:
  run_report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.1.3'
      - run: |
          gem install bundler
          bundle install
          GITHUB_TOKEN=$(bundle exec ruby token_crafter.rb)
          OUTPUT=$(bundle exec ruby dependabot_report.rb)
          echo 'REPORT_OUTPUT<<EOF' >> $GITHUB_ENV
          echo "$OUTPUT" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
        env:
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Post to Slack
        uses: archive/github-actions-slack@v2.6.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel: ${{ env.SLACK_CHANNEL }}
          slack-text: ${{ env.REPORT_OUTPUT }}
